// src/Lessons/Unit01/U01L01/U01L01.js
import React, { useState } from 'react';
import LessonItem from './LessonItem';

const Unit01Array = [
	{
		id: 'U01L01',
		section: 'Unit 01',
		title: 'Lesson 01',
		subtitle: 'Intro to Problem Solving',
		content: 'Links to Files and Resources for Unit 01 Lesson 01 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L01-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L01-Slideshow.pdf',
	},
	{
		id: 'U01L02',
		section: 'Unit 01',
		title: 'Lesson 02',
		subtitle: 'The Problem Solving Process',
		content: 'Links to Files and Resources for Unit 01 Lesson 02 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L02-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L02-Slideshow.pdf',
	},
	{
		id: 'U01L03',
		section: 'Unit 01',
		title: 'Lesson 03',
		subtitle: 'Exploring Problem Solving',
		content: 'Links to Files and Resources for Unit 01 Lesson 03 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L03-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L03-Slideshow.pdf',
	},
	{
		id: 'U01L04',
		section: 'Unit 01',
		title: 'Lesson 04',
		subtitle: 'What Is A Computer',
		content: 'Links to Files and Resources for Unit 01 Lesson 04 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L04-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L04-Slideshow.pdf',
	},
	{
		id: 'U01L05',
		section: 'Unit 01',
		title: 'Lesson 05',
		subtitle: 'Input and Output',
		content: 'Links to Files and Resources for Unit 01 Lesson 05 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L05-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L05-Slideshow.pdf',
	},
	{
		id: 'U01L06',
		section: 'Unit 01',
		title: 'Lesson 06',
		subtitle: 'Processing',
		content: 'Links to Files and Resources for Unit 01 Lesson 06 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L06-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L06-Slideshow.pdf',
	},
	{
		id: 'U01L07',
		section: 'Unit 01',
		title: 'Lesson 07',
		subtitle: 'Storage',
		content: 'Links to Files and Resources for Unit 01 Lesson 07 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L07-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L07-Slideshow.pdf',
	},
	{
		id: 'U01L08',
		section: 'Unit 01',
		title: 'Lesson 08',
		subtitle: 'Project: Propose An App',
		content: 'Links to Files and Resources for Unit 01 Lesson 08 will go here!?!',
		activity: './Lessons/Unit01/ActivityGuide/U01_L08-ActivityGuide.pdf',
		slideshow: './Lessons/Unit01/Slideshows/U01_L08-Slideshow.pdf',
	},
];

const Unit02Array = [
	{
		id: 'U02L01',
		section: 'Unit 02',
		title: 'Lesson 01',
		subtitle: 'Exploring Web Pages',
		content: 'Links to Files and Resources for Unit 02 Lesson 01 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L01-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L01-Slideshow.pdf',
	},
	{
		id: 'U02L02',
		section: 'Unit 02',
		title: 'Lesson 02',
		subtitle: 'Intro to HTML',
		content: 'Links to Files and Resources for Unit 02 Lesson 02 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L02-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L02-Slideshow.pdf',
	},
	{
		id: 'U02L03',
		section: 'Unit 02',
		title: 'Lesson 03',
		subtitle: 'Headings and Lists',
		content: 'Links to Files and Resources for Unit 02 Lesson 03 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L03-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L03-Slideshow.pdf',
	},
	{
		id: 'U02L04',
		section: 'Unit 02',
		title: 'Lesson 04',
		subtitle: 'Digital Footprint',
		content: 'Links to Files and Resources for Unit 02 Lesson 04 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L04-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L04-Slideshow.pdf',
	},
	{
		id: 'U02L05',
		section: 'Unit 02',
		title: 'Lesson 05',
		subtitle: 'Mini-Project: HTML Web Page',
		content: 'Links to Files and Resources for Unit 02 Lesson 05 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L05-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L05-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U02L06',
		section: 'Unit 02',
		title: 'Lesson 06',
		subtitle: 'Styling Text With CSS',
		content: 'Links to Files and Resources for Unit 02 Lesson 06 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L06-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L06-Slideshow.pdf',
	},
	{
		id: 'U02L07',
		section: 'Unit 02',
		title: 'Lesson 07',
		subtitle: 'Intellectual Property',
		content: 'Links to Files and Resources for Unit 02 Lesson 07 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L07-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L07-Slideshow.pdf',
	},
	{
		id: 'U02L08',
		section: 'Unit 02',
		title: 'Lesson 08',
		subtitle: 'Using Images',
		content: 'Links to Files and Resources for Unit 02 Lesson 08 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L08-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L08-Slideshow.pdf',
	},
	{
		id: 'U02L09',
		section: 'Unit 02',
		title: 'Lesson 09',
		subtitle: 'Styling Elements With CSS',
		content: 'Links to Files and Resources for Unit 02 Lesson 09 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L09-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L09-Slideshow.pdf',
	},
	{
		id: 'U02L10',
		section: 'Unit 02',
		title: 'Lesson 10',
		subtitle: 'Mini-Project: Adding Style to a Web Page',
		content: 'Links to Files and Resources for Unit 02 Lesson 10 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L10-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L10-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U02L11',
		section: 'Unit 02',
		title: 'Lesson 11',
		subtitle: 'CSS Classes',
		content: 'Links to Files and Resources for Unit 02 Lesson 11 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L11-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L11-Slideshow.pdf',
	},
	{
		id: 'U02L12',
		section: 'Unit 02',
		title: 'Lesson 12',
		subtitle: 'Organizing Content with Flexbox',
		content: 'Links to Files and Resources for Unit 02 Lesson 12 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L12-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L12-Slideshow.pdf',
	},
	{
		id: 'U02L13',
		section: 'Unit 02',
		title: 'Lesson 13',
		subtitle: 'Flexbox Children for More Control',
		content: 'Links to Files and Resources for Unit 02 Lesson 13 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L13-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L13-Slideshow.pdf',
	},
	{
		id: 'U02L14',
		section: 'Unit 02',
		title: 'Lesson 14',
		subtitle: 'Chapter 1 Project',
		content: 'Links to Files and Resources for Unit 02 Lesson 14 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L14-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L14-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U02L15',
		section: 'Unit 02',
		title: 'Lesson 15',
		subtitle: 'Team Problem Solving',
		content: 'Links to Files and Resources for Unit 02 Lesson 15 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L15-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L15-Slideshow.pdf',
	},
	{
		id: 'U02L16',
		section: 'Unit 02',
		title: 'Lesson 16',
		subtitle: 'Sources and Research',
		content: 'Links to Files and Resources for Unit 02 Lesson 16 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L16-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L16-Slideshow.pdf',
	},
	{
		id: 'U02L17',
		section: 'Unit 02',
		title: 'Lesson 17',
		subtitle: 'Linking Pages',
		content: 'Links to Files and Resources for Unit 02 Lesson 17 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L17-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L17-Slideshow.pdf',
	},
	{
		id: 'U02L18',
		section: 'Unit 02',
		title: 'Lesson 18',
		subtitle: 'CSS Pseudo-classes',
		content: 'Links to Files and Resources for Unit 02 Lesson 18 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L18-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L18-Slideshow.pdf',
	},
	{
		id: 'U02L19',
		section: 'Unit 02',
		title: 'Lesson 19',
		subtitle: 'Planning a Multi-Page Site',
		content: 'Links to Files and Resources for Unit 02 Lesson 19 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L19-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L19-Slideshow.pdf',
	},
	{
		id: 'U02L20',
		section: 'Unit 02',
		title: 'Lesson 20',
		subtitle: 'Project: Website for a Purpose',
		content: 'Links to Files and Resources for Unit 02 Lesson 20 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L20-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L20-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U02L21',
		section: 'Unit 02',
		title: 'Lesson 21',
		subtitle: 'Peer Review and Final Touches',
		content: 'Links to Files and Resources for Unit 02 Lesson 21 will go here!?!',
		activity: './Lessons/Unit02/ActivityGuide/U02_L21-ActivityGuide.pdf',
		slideshow: './Lessons/Unit02/Slideshows/U02_L21-Slideshow.pdf',
	}
];

const Unit03Array = [
	{
		id: 'U03L01',
		section: 'Unit 03',
		title: 'Lesson 01',
		subtitle: 'Programming for a Purpose',
		content: 'Links to Files and Resources for Unit 03 Lesson 01 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L01-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L01-Slideshow.pdf',
	},
	{
		id: 'U03L02',
		section: 'Unit 03',
		title: 'Lesson 02',
		subtitle: 'Plotting Shapes',
		content: 'Links to Files and Resources for Unit 03 Lesson 02 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L02-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L02-Slideshow.pdf',
	},
	{
		id: 'U03L03',
		section: 'Unit 03',
		title: 'Lesson 03',
		subtitle: 'Drawing in Game Lab',
		content: 'Links to Files and Resources for Unit 03 Lesson 03 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L03-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L03-Slideshow.pdf',
	},
	{
		id: 'U03L04',
		section: 'Unit 03',
		title: 'Lesson 04',
		subtitle: 'Shapes and Parameters',
		content: 'Links to Files and Resources for Unit 03 Lesson 04 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L04-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L04-Slideshow.pdf',
	},
	{
		id: 'U03L05',
		section: 'Unit 03',
		title: 'Lesson 05',
		subtitle: 'Variables',
		content: 'Links to Files and Resources for Unit 03 Lesson 05 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L05-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L05-Slideshow.pdf',
	},
	{
		id: 'U03L06',
		section: 'Unit 03',
		title: 'Lesson 06',
		subtitle: 'Random Numbers',
		content: 'Links to Files and Resources for Unit 03 Lesson 06 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L06-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L06-Slideshow.pdf',
	},
	{
		id: 'U03L07',
		section: 'Unit 03',
		title: 'Lesson 07',
		subtitle: 'Mini-Project: Robot Faces',
		content: 'Links to Files and Resources for Unit 03 Lesson 07 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L07-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L07-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L08',
		section: 'Unit 03',
		title: 'Lesson 08',
		subtitle: 'Sprites',
		content: 'Links to Files and Resources for Unit 03 Lesson 08 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L08-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L08-Slideshow.pdf',
	},
	{
		id: 'U03L09',
		section: 'Unit 03',
		title: 'Lesson 09',
		subtitle: 'Sprite Properties',
		content: 'Links to Files and Resources for Unit 03 Lesson 09 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L09-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L09-Slideshow.pdf',
	},
	{
		id: 'U03L10',
		section: 'Unit 03',
		title: 'Lesson 10',
		subtitle: 'Text',
		content: 'Links to Files and Resources for Unit 03 Lesson 10 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L10-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L10-Slideshow.pdf',
	},
	{
		id: 'U03L11',
		section: 'Unit 03',
		title: 'Lesson 11',
		subtitle: 'Mini-Project: Captioned Scenes',
		content: 'Links to Files and Resources for Unit 03 Lesson 11 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L11-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L11-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L12',
		section: 'Unit 03',
		title: 'Lesson 12',
		subtitle: 'The Draw Loop',
		content: 'Links to Files and Resources for Unit 03 Lesson 12 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L12-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L12-Slideshow.pdf',
	},
	{
		id: 'U03L13',
		section: 'Unit 03',
		title: 'Lesson 13',
		subtitle: 'Sprite Movement',
		content: 'Links to Files and Resources for Unit 03 Lesson 13 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L13-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L13-Slideshow.pdf',
	},
	{
		id: 'U03L14',
		section: 'Unit 03',
		title: 'Lesson 14',
		subtitle: 'Mini-Project: Animation',
		content: 'Links to Files and Resources for Unit 03 Lesson 14 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L14-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L14-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L15',
		section: 'Unit 03',
		title: 'Lesson 15',
		subtitle: 'Conditionals',
		content: 'Links to Files and Resources for Unit 03 Lesson 15 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L15-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L15-Slideshow.pdf',
	},
	{
		id: 'U03L16',
		section: 'Unit 03',
		title: 'Lesson 16',
		subtitle: 'Keyboard Input',
		content: 'Links to Files and Resources for Unit 03 Lesson 16 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L16-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L16-Slideshow.pdf',
	},
	{
		id: 'U03L17',
		section: 'Unit 03',
		title: 'Lesson 17',
		subtitle: 'Mouse Input',
		content: 'Links to Files and Resources for Unit 03 Lesson 17 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L17-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L17-Slideshow.pdf',
	},
	{
		id: 'U03L18',
		section: 'Unit 03',
		title: 'Lesson 18',
		subtitle: 'Project: Interactive Card',
		content: 'Links to Files and Resources for Unit 03 Lesson 18 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L18-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L18-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L19',
		section: 'Unit 03',
		title: 'Lesson 19',
		subtitle: 'Velocity',
		content: 'Links to Files and Resources for Unit 03 Lesson 19 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L19-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L19-Slideshow.pdf',
	},
	{
		id: 'U03L20',
		section: 'Unit 03',
		title: 'Lesson 20',
		subtitle: 'Collision Detection',
		content: 'Links to Files and Resources for Unit 03 Lesson 20 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L20-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L20-Slideshow.pdf',
	},
	{
		id: 'U03L21',
		section: 'Unit 03',
		title: 'Lesson 21',
		subtitle: 'Mini-Project: Side Scroller',
		content: 'Links to Files and Resources for Unit 03 Lesson 21 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L21-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L21-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L22',
		section: 'Unit 03',
		title: 'Lesson 22',
		subtitle: 'Complex Sprite Movement',
		content: 'Links to Files and Resources for Unit 03 Lesson 22 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L22-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L22-Slideshow.pdf',
	},
	{
		id: 'U03L23',
		section: 'Unit 03',
		title: 'Lesson 23',
		subtitle: 'Collisions',
		content: 'Links to Files and Resources for Unit 03 Lesson 23 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L23-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L23-Slideshow.pdf',
	},
	{
		id: 'U03L24',
		section: 'Unit 03',
		title: 'Lesson 24',
		subtitle: 'Mini-Project: Flyer Game',
		content: 'Links to Files and Resources for Unit 03 Lesson 24 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L24-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L24-Slideshow.pdf',
		specialClass: 'go-tomato',
	},
	{
		id: 'U03L25',
		section: 'Unit 03',
		title: 'Lesson 25',
		subtitle: 'Functions',
		content: 'Links to Files and Resources for Unit 03 Lesson 25 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L25-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L25-Slideshow.pdf',
	},
	{
		id: 'U03L26',
		section: 'Unit 03',
		title: 'Lesson 26',
		subtitle: 'The Game Design Process',
		content: 'Links to Files and Resources for Unit 03 Lesson 26 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L26-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L26-Slideshow.pdf',
	},
	{
		id: 'U03L27',
		section: 'Unit 03',
		title: 'Lesson 27',
		subtitle: 'Using the Game Design Process',
		content: 'Links to Files and Resources for Unit 03 Lesson 27 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L27-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L27-Slideshow.pdf',
	},
	{
		id: 'U03L28',
		section: 'Unit 03',
		title: 'Lesson 28',
		subtitle: 'Project: Design a Game',
		content: 'Links to Files and Resources for Unit 03 Lesson 28 will go here!?!',
		activity: './Lessons/Unit03/ActivityGuide/U03_L28-ActivityGuide.pdf',
		slideshow: './Lessons/Unit03/Slideshows/U03_L28-Slideshow.pdf',
		specialClass: 'go-tomato',
	}
];


export { Unit01Array, Unit02Array, Unit03Array };

const LessonArray = ({ lesson, selectedLessonId, setSelectedLessonId }) => {
	return (
		<div>
			<h1>{lesson.title}</h1>
			<p>{lesson.content}</p>
			<a href={lesson.activity}>Activity Guide</a>
			<a href={lesson.slideshow}>Slideshow</a>
		</div>
	);
};
export default LessonArray;

// export { Unit01Array, Unit02Array };

// // src/Lessons/Unit01/U01L01/U01L01.js
// import React from 'react';
// import LessonTemplate from '../../components/LessonTemplate';
//
// const U01L01content = () => {
//   const title = "Unit 01 - LessonArray 01";
//   const content = "Links to Files and Resources for Unit 01 LessonArray 01 will go here!!!";
//
//   return <LessonTemplate title={title} content={content} />;
// };
//
// export default U01L01content;
