// src/LessonData.js
export const unit01Lessons = [
  { id: 'U01L01', title: 'Lesson 01 - Intro to Problem Solving' },
  { id: 'U01L02', title: 'Lesson 02 - The Problem Solving Process' },
  { id: 'U01L03', title: 'Lesson 03 - Exploring Problem Solving' },
  { id: 'U01L04', title: 'Lesson 04 - What Is A Computer' },
  { id: 'U01L05', title: 'Lesson 05 - Input and Output' },
  { id: 'U01L06', title: 'Lesson 06 - Processing' },
  { id: 'U01L07', title: 'Lesson 07 - Storage' },
  { id: 'U01L08', title: 'Lesson 08 - Project: Propose An App' },
];

export const unit02Lessons = [
  { id: 'U02L01', title: 'Lesson 01 - Exploring Web Pages' },
  { id: 'U02L02', title: 'Lesson 02 - Intro to HTML' },
  { id: 'U02L03', title: 'Lesson 03 - Headings and Lists' },
  { id: 'U02L04', title: 'Lesson 04 - Digital Footprint' },
  { id: 'U02L05', title: 'Lesson 05 - Mini-Project: HTML Web Page', specialClass: 'go-tomato' },
  { id: 'U02L06', title: 'Lesson 06 - Styling Text With CSS' },
  { id: 'U02L07', title: 'Lesson 07 - Intellectual Property' },
  { id: 'U02L08', title: 'Lesson 08 - Using Images' },
  { id: 'U02L09', title: 'Lesson 09 - Styling Elements With CSS' },
  { id: 'U02L10', title: 'Lesson 10 - Mini-Project: Adding Style to a Web Page', specialClass: 'go-tomato' },
  { id: 'U02L11', title: 'Lesson 11 - CSS Classes' },
  { id: 'U02L12', title: 'Lesson 12 - Organizing Content with Flexbox' },
  { id: 'U02L13', title: 'Lesson 13 - Flexbox Children for More Control' },
  { id: 'U02L14', title: 'Lesson 14 - Chapter 1 Project', specialClass: 'go-tomato' },
  { id: 'U02L15', title: 'Lesson 15 - Team Problem Solving' },
  { id: 'U02L16', title: 'Lesson 16 - Sources and Research' },
  { id: 'U02L17', title: 'Lesson 17 - Linking Pages' },
  { id: 'U02L18', title: 'Lesson 18 - CSS Pseudo-classes' },
  { id: 'U02L19', title: 'Lesson 19 - Planning a Multi-Page Site' },
  { id: 'U02L20', title: 'Project: Website for a Purpose', specialClass: 'go-tomato' },
  { id: 'U02L21', title: 'Lesson 21 - Peer Review and Final Touches' },
];

export const unit03Lessons = [
  { id: 'U03L01', title: 'Lesson 01 - Programming for a Purpose' },
  { id: 'U03L02', title: 'Lesson 02 - Plotting Shapes' },
  { id: 'U03L03', title: 'Lesson 03 - Drawing in Game Lab' },
  { id: 'U03L04', title: 'Lesson 04 - Shapes and Parameters' },
  { id: 'U03L05', title: 'Lesson 05 - Variables' },
  { id: 'U03L06', title: 'Lesson 06 - Random Numbers' },
  { id: 'U03L07', title: 'Lesson 07 - Mini-Project: Robot Faces', specialClass: 'go-tomato' },
  { id: 'U03L08', title: 'Lesson 08 - Sprites' },
  { id: 'U03L09', title: 'Lesson 09 - Sprite Properties' },
  { id: 'U03L10', title: 'Text' },
  { id: 'U03L11', title: 'Mini-Project: Captioned Scenes', specialClass: 'go-tomato' },
  { id: 'U03L12', title: 'The Draw Loop' },
  { id: 'U03L13', title: 'Sprite Movement' },
  { id: 'U03L14', title: 'Mini-Project: Animation', specialClass: 'go-tomato' },
  { id: 'U03L15', title: 'Conditionals' },
  { id: 'U03L16', title: 'Keyboard Input' },
  { id: 'U03L17', title: 'Mouse Input' },
  { id: 'U03L18', title: 'Project: Interactive Card', specialClass: 'go-tomato' },
  { id: 'U03L19', title: 'Velocity' },
  { id: 'U03L20', title: 'Collision Detection' },
  { id: 'U03L21', title: 'Mini-Project: Side Scroller', specialClass: 'go-tomato' },
  { id: 'U03L22', title: 'Complex Sprite Movement' },
  { id: 'U03L23', title: 'Collisions' },
  { id: 'U03L24', title: 'Mini-Project: Flyer Game', specialClass: 'go-tomato' },
  { id: 'U03L25', title: 'Functions' },
  { id: 'U03L26', title: 'The Game Design Process' },
  { id: 'U03L27', title: 'Using the Game Design Process' },
  { id: 'U03L28', title: 'Project: Design a Game', specialClass: 'go-tomato' },
];
